apply plugin: 'net.corda.plugins.quasar-utils'

description 'Corda Business Networks Integration Demo - workflows'

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlinVersion"

    cordaProvided "$cordaReleaseGroup:corda-core:$cordaVersion"

    // Corda integration dependencies
    cordapp project(':business-networks-workflows')
    cordapp project(':business-networks-contracts')
    cordapp project(':business-networks-demo:business-networks-demo-contracts')

    testImplementation "org.jetbrains.kotlin:kotlin-test:$kotlinVersion"

    testImplementation("$cordaReleaseGroup:corda-core-test-utils:$cordaVersion") {
        exclude group: 'co.paralleluniverse', module: 'quasar-core'
    }

    testImplementation("$cordaReleaseGroup:corda-node-driver:$cordaVersion") {
        exclude group: 'co.paralleluniverse', module: 'quasar-core'
    }
}

cordapp {
    targetPlatformVersion cordaPlatformVersion.toInteger()
    minimumPlatformVersion cordaPlatformVersion.toInteger()
    workflow {
        name "Corda Business Networks Integration Demo"
        versionId 1
        vendor "R3"
        licence "Open Source (Apache 2)"
    }
}

test {
    jvmArgs = rootProject.ext.testJvmArgs
}