apply plugin: 'net.corda.plugins.quasar-utils'

description 'Corda Business Networks Integration Demo - workflows'

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlinVersion"

    cordaProvided "$cordaReleaseGroup:corda-core:$cordaVersion"

    // Corda integration dependencies
    cordapp project(':business-networks-workflows')
    cordapp project(':business-networks-contracts')
    cordapp project(':business-networks-demo:business-networks-demo-contracts')

    testImplementation "org.jetbrains.kotlin:kotlin-test:$kotlinVersion"

    testImplementation("$cordaReleaseGroup:corda-core-test-utils:$cordaVersion") {
        exclude group: 'co.paralleluniverse', module: 'quasar-core'
    }

    testImplementation("$cordaReleaseGroup:corda-node-driver:$cordaVersion") {
        exclude group: 'co.paralleluniverse', module: 'quasar-core'
    }
}

cordapp {
    targetPlatformVersion cordaPlatformVersion.toInteger()
    minimumPlatformVersion cordaPlatformVersion.toInteger()
    workflow {
        name "Corda Business Networks Integration Demo"
        versionId 1
        vendor "R3"
        licence "Open Source (Apache 2)"
    }
}

quasar {
    excludePackages.addAll(
            "antlr**",
            "com.codahale**",
            "com.fasterxml.**",
            "com.github.benmanes.caffeine.**",
            "com.google.**",
            "com.lmax.**",
            "com.zaxxer.**",
            "net.bytebuddy**",
            "io.github.classgraph**",
            "io.netty*",
            "liquibase**",
            "net.i2p.crypto.**",
            "nonapi.io.github.classgraph.**",
            "org.apiguardian.**",
            "org.bouncycastle**",
            "org.codehaus.**",
            "org.h2**",
            "org.hibernate**",
            "org.jboss.**",
            "org.objenesis**",
            "org.w3c.**",
            "org.xml**",
            "org.yaml**",
            "rx**",
            "kotlin**"
    )
}

test {
    jvmArgs = rootProject.ext.testJvmArgs
}