description 'Corda Business Networks Contracts'

cordapp {
    targetPlatformVersion cordaPlatformVersion.toInteger()
    minimumPlatformVersion cordaPlatformVersion.toInteger()
    contract {
        name "Business Networks Showcase"
        vendor "Corda Open Source"
        versionId 1
        licence "Open Source (Apache 2)"
    }
}

dependencies {
    implementation 'javax.persistence:javax.persistence-api:2.2'
    cordaProvided "$cordaReleaseGroup:corda-core:$cordaVersion"
    testImplementation"$cordaReleaseGroup:corda-core-test-utils:$cordaVersion"
    testImplementation "$cordaReleaseGroup:corda-test-utils:$cordaVersion"
    testImplementation"$cordaReleaseGroup:corda-node-driver:$cordaVersion"
    testImplementation "org.jetbrains.kotlin:kotlin-test:$kotlinVersion"
    testImplementation "org.mockito.kotlin:mockito-kotlin:$mockitoKotlinVersion"
    testImplementation "org.mockito:mockito-core:$mockitoVersion"
    testImplementation "junit:junit:$junitVersion"
}

jar {
    duplicatesStrategy(DuplicatesStrategy.EXCLUDE)
}

test {
    jvmArgs = rootProject.ext.testJvmArgs
}