description 'Corda Business Networks'

cordapp {
    targetPlatformVersion cordaPlatformVersion.toInteger()
    minimumPlatformVersion cordaPlatformVersion.toInteger()
    workflow {
        name "Business Networks Showcase"
        vendor "Corda Open Source"
        versionId 1
        licence "Open Source (Apache 2)"
    }
}

sourceSets {
    integrationTest {
        kotlin {
            compileClasspath += main.output + test.output
            runtimeClasspath += main.output + test.output
            srcDir file('src/integration-test/kotlin')
        }
        resources {
            srcDir file('src/integration-test/resources')
        }
    }
}

configurations {
    testArtifacts.extendsFrom testImplementation
    integrationTestCompile.extendsFrom testImplementation
    integrationTestRuntimeOnly.extendsFrom testRuntimeOnly
}

dependencies {
    cordapp project(":business-networks-contracts")

    cordaProvided ("$cordaReleaseGroup:corda-node-api:$cordaVersion") {
        exclude group: "ch.qos.logback", module: "logback-classic"
    }
    corda("$cordaReleaseGroup:corda:$cordaVersion") {
        exclude group: 'co.paralleluniverse', module: 'quasar-core'
    }
    cordaProvided ("$cordaReleaseGroup:corda-node:$cordaVersion")

        cordaProvided "$cordaReleaseGroup:corda-core:$cordaVersion"
    cordaProvided "$cordaReleaseGroup:corda-jackson:$cordaVersion"

    testImplementation("$cordaReleaseGroup:corda-core-test-utils:$cordaVersion") {
        exclude group: 'co.paralleluniverse', module: 'quasar-core'
    }

    testImplementation("$cordaReleaseGroup:corda-node-driver:$cordaVersion") {
        exclude group: 'co.paralleluniverse', module: 'quasar-core'
    }

    testImplementation "org.jetbrains.kotlin:kotlin-test:$kotlinVersion"
    testImplementation "org.mockito.kotlin:mockito-kotlin:$mockitoKotlinVersion"
    testImplementation "org.mockito:mockito-core:$mockitoVersion"
    testImplementation "junit:junit:$junitVersion"

    cordaProvided "com.fasterxml.jackson.module:jackson-module-kotlin:2.15.3"
}

test.maxHeapSize = "2g"

task integrationTest(type: Test, dependsOn: []) {
    testClassesDirs = sourceSets.integrationTest.output.classesDirs
    classpath = sourceSets.integrationTest.runtimeClasspath
    maxHeapSize = "2g"
}

test {
    jvmArgs = rootProject.ext.testJvmArgs
}