description 'Corda Business Networks'

cordapp {
    targetPlatformVersion cordaPlatformVersion.toInteger()
    minimumPlatformVersion cordaPlatformVersion.toInteger()
    workflow {
        name "Business Networks Showcase"
        vendor "Corda Open Source"
        versionId 1
        licence "Open Source (Apache 2)"
    }
}

sourceSets {
    integrationTest {
        kotlin {
            compileClasspath += main.output + test.output
            runtimeClasspath += main.output + test.output
            srcDir file('src/integration-test/kotlin')
        }
        resources {
            srcDir file('src/integration-test/resources')
        }
    }
}

configurations {
    testArtifacts.extendsFrom testImplementation
    integrationTestImplementation.extendsFrom testImplementation
    integrationTestRuntime.extendsFrom testRuntime
}

dependencies {
    cordapp project(":business-networks-contracts")

    cordaProvided ("$cordaReleaseGroup:corda-node-api:$cordaVersion") {
        exclude group: "ch.qos.logback", module: "logback-classic"
    }
    corda("$cordaReleaseGroup:corda:$cordaVersion") {
        exclude group: 'co.paralleluniverse', module: 'quasar-core'
    }
    cordaProvided ("$cordaReleaseGroup:corda-node:$cordaVersion")

    cordaProvided "$cordaReleaseGroup:corda-core:$cordaVersion"
    cordaProvided "$cordaReleaseGroup:corda-jackson:$cordaVersion"

    testImplementation("$cordaReleaseGroup:corda-core-test-utils:$cordaVersion") {
        exclude group: 'co.paralleluniverse', module: 'quasar-core'
    }

    testImplementation("$cordaReleaseGroup:corda-node-driver:$cordaVersion") {
        exclude group: 'co.paralleluniverse', module: 'quasar-core'
    }

    testImplementation "org.jetbrains.kotlin:kotlin-test:$kotlinVersion"
    testImplementation "org.mockito.kotlin:mockito-kotlin:$mockitoKotlinVersion"
    testImplementation "org.mockito:mockito-core:$mockitoVersion"
    testImplementation "junit:junit:$junitVersion"

    cordaProvided "com.fasterxml.jackson.module:jackson-module-kotlin:2.15.3"
}

quasar {
    excludePackages.addAll(
            "antlr**",
            "com.codahale**",
            "com.fasterxml.**",
            "com.github.benmanes.caffeine.**",
            "com.google.**",
            "com.lmax.**",
            "com.zaxxer.**",
            "net.bytebuddy**",
            "io.github.classgraph**",
            "io.netty*",
            "liquibase**",
            "net.i2p.crypto.**",
            "nonapi.io.github.classgraph.**",
            "org.apiguardian.**",
            "org.bouncycastle**",
            "org.codehaus.**",
            "org.h2**",
            "org.hibernate**",
            "org.jboss.**",
            "org.objenesis**",
            "org.w3c.**",
            "org.xml**",
            "org.yaml**",
            "rx**",
            "kotlin**"
    )
}

test.maxHeapSize = "2g"

task integrationTest(type: Test, dependsOn: []) {
    testClassesDirs = sourceSets.integrationTest.output.classesDirs
    classpath = sourceSets.integrationTest.runtimeClasspath
    maxHeapSize = "2g"
    jvmArgs testJvmArgs
}